sudo: required
services:
  -docker

before_install:
  -docker build -t tacobell1988/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tacobell1988/react-test npm test -- --coverage

after_success:
  - docker build -t tacobell1988/multi-client ./client
  - docker build -t tacobell1988/multi-nginx ./nginx
  - docker build -t tacobell1988/multi-server ./server
  - docker build -t tacobell1988/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take above images and push to docker hub
  - docker push tacobell1988/multi-client
  - docker push tacobell1988/multi-nginx
  - docker push tacobell1988/multi-server
  - docker push tacobell1988/multi-worker