sudo: required
services:
  - docker

before_install:
  - docker build -t tacobell1988/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tacobell1988/react-test npm test

after_success:
  - docker build -t tacobell1988/multi-client ./client
  - docker build -t tacobell1988/multi-nginx ./nginx
  - docker build -t tacobell1988/multi-server ./server
  - docker build -t tacobell1988/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take above images and push to docker hub
  - docker push tacobell1988/multi-client
  - docker push tacobell1988/multi-nginx
  - docker push tacobell1988/multi-server
  - docker push tacobell1988/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-239811604678
  bucket: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY